<a href="https://colab.research.google.com/github/Abhilitcode/DaveAI_Internship/blob/main/viterbi_algorithm_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In Python, using **NumPy**, the differentiation between **2D** and **3D** arrays comes down to the number of dimensions (or axes) they have. Here’s how to differentiate between them in terms of **syntax** and **concept**:

### 2D Array (Matrix):
- A **2D array** has two dimensions: **rows** and **columns**.
- Think of it as a table or matrix where each element is accessed by two indices: one for the row and one for the column.

#### Example:
```python
import numpy as np

# 2D Array (Matrix)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print(array_2d)
```

**Shape**: A 2D array has a shape of `(rows, columns)`. In this example:
```python
array_2d.shape  # Output: (3, 3)
```
This means there are 3 rows and 3 columns.

### 3D Array:
- A **3D array** adds an additional dimension: **depth** (or layers).
- It’s essentially an array of 2D arrays, where each element is accessed by three indices: one for the layer, one for the row, and one for the column.

#### Example:
```python
import numpy as np

# 3D Array (Tensor)
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]],
                     
                     [[10, 11, 12],
                      [13, 14, 15],
                      [16, 17, 18]]])

print(array_3d)
```

**Shape**: A 3D array has a shape of `(layers, rows, columns)`. In this example:
```python
array_3d.shape  # Output: (2, 3, 3)
```
This means there are 2 layers (or "slices"), and each layer is a 3x3 matrix (3 rows, 3 columns).

### Key Differences:

1. **Dimensions**:
   - **2D array**: Only two indices (rows, columns) are needed to access elements.
   - **3D array**: Three indices (layers, rows, columns) are needed to access elements.

2. **Shape**:
   - **2D array**: `(rows, columns)`, e.g., (3, 3).
   - **3D array**: `(layers, rows, columns)`, e.g., (2, 3, 3).

### Accessing Elements:

- **2D Array**:
  To access the element at row 2, column 1 in `array_2d`:
  ```python
  array_2d[1, 0]  # Output: 4 (2nd row, 1st column)
  ```

- **3D Array**:
  To access the element in the 2nd layer, 2nd row, and 1st column in `array_3d`:
  ```python
  array_3d[1, 1, 0]  # Output: 13 (2nd layer, 2nd row, 1st column)
  ```

### When to Use 2D vs 3D Arrays:
- **2D arrays** are useful for handling data that can be represented in rows and columns (like tables, matrices).
- **3D arrays** are used when you have multiple sets of 2D arrays, such as in:
  - **Image processing** (where you have color channels as layers),
  - **Video data** (where each frame is a 2D array),
  - **Tensors** in machine learning (e.g., multi-dimensional data).

In summary:
- **2D**: Think rows and columns (table/matrix).
- **3D**: Think layers of 2D matrices stacked together.

In [1]:
import numpy as np

define states and obsevations

In [2]:
states = ['Sunny', 'Cloudy', 'Rainy']
observations = ['Sunglasses', 'Jacket', 'Umbrella']

In [3]:
n_states = len(states)

In [4]:
n_states

3

In [5]:
n_observations = len(observations)

In [6]:
n_observations

3

In [7]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
arr.ndim

2

In [9]:
arr.shape

(3, 3)

In [10]:
#transition probability sample
transition_prob = np.array([[0.7,0.2,0.1],[0.3,0.4,0.3],[0.2,0.3,0.5]])

In [11]:
transition_prob

array([[0.7, 0.2, 0.1],
       [0.3, 0.4, 0.3],
       [0.2, 0.3, 0.5]])

In [12]:
emission_prob = np.array([[0.8, 0.2, 0.0], [0.2, 0.6, 0.2],  [0.1, 0.3, 0.6]])

In [13]:
emission_prob

array([[0.8, 0.2, 0. ],
       [0.2, 0.6, 0.2],
       [0.1, 0.3, 0.6]])

initial_prob: This array gives the probability of starting in each of the possible states. For example:
There’s a 60% chance the day starts Sunny, 30% chance it starts Cloudy, and 10% chance it starts Rainy.
Why we need it: The initial state is unknown, so we use this to model where we think the system starts.

In [14]:
initial_prob = np.array([0.6, 0.3, 0.1])  # P(Sunny), P(Cloudy), P(Rainy)

In [15]:
initial_prob

array([0.6, 0.3, 0.1])

In [16]:
observation_seq = ['Sunglasses', 'Jacket', 'Umbrella']

In the line `observations.index(obs)`, **`observations`** refers to the list of observable events that you defined earlier in the code:

```python
observations = ['Sunglasses', 'Jacket', 'Umbrella']
```

The list `observations` contains the possible things you can observe in your Hidden Markov Model (HMM). Each item in the `observation_sequence` (which represents the observed events) is converted to its corresponding index in this list.

For example, if your `observation_sequence` is `['Sunglasses', 'Jacket', 'Umbrella']`, then:
- `'Sunglasses'` has an index of `0` in the `observations` list,
- `'Jacket'` has an index of `1`,
- `'Umbrella'` has an index of `2`.

The line `observations.index(obs)` finds the index of a particular observation (`obs`) in the `observations` list, which is later used in the Viterbi algorithm to match the observations with emission probabilities.

In [17]:
obs_indices = [observations.index(obs) for obs in observation_seq]

In [18]:
obs_indices

[0, 1, 2]

In [28]:
T = len(obs_indices)

In [29]:
V = np.zeros((n_states, T))

In [30]:
V

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
path = np.zeros((n_states, T), dtype=int)

In [32]:
path

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Yes, exactly! After the initialization step, for the first observation (**Sunglasses** at time step 0), you will have calculated the initial probability for each state (Sunny, Cloudy, Rainy).

Here’s a summary of how those initial probabilities are computed:

1. **For Sunny at t=0**:
   \[
   V[\text{Sunny}, 0] = \text{Initial Prob(Sunny)} \times \text{Emission Prob(Sunglasses | Sunny)} = 0.6 \times 0.8 = 0.48
   \]

2. **For Cloudy at t=0**:
   \[
   V[\text{Cloudy}, 0] = \text{Initial Prob(Cloudy)} \times \text{Emission Prob(Sunglasses | Cloudy)} = 0.3 \times 0.2 = 0.06
   \]

3. **For Rainy at t=0**:
   \[
   V[\text{Rainy}, 0] = \text{Initial Prob(Rainy)} \times \text{Emission Prob(Sunglasses | Rainy)} = 0.1 \times 0.1 = 0.01
   \]

These values will be stored in the `V` matrix, which keeps track of the maximum probabilities for each state at each time step.

So, for **Sunglasses** (the first observation at `t=0`), the initial probabilities are:
- `V[Sunny, 0] = 0.48`
- `V[Cloudy, 0] = 0.06`
- `V[Rainy, 0] = 0.01`

These values represent the likelihood of starting in each state and observing **Sunglasses** at time step 0.

In [24]:
for s in range(n_states):
  v[s,0] = initial_prob[s] * emission_prob[s, obs_indices[0]]
  path[s,0] = s
  print(v[s,0])
  print(path)


0.48
[[0 0 0]
 [0 0 0]
 [0 0 0]]
0.06
[[0 0 0]
 [1 0 0]
 [0 0 0]]
0.010000000000000002
[[0 0 0]
 [1 0 0]
 [2 0 0]]


In [34]:
# Viterbi algorithm implementation
def viterbi(obs_indices, transition_prob, emission_prob, initial_prob):
    # Number of time steps (observations)
    T = len(obs_indices)

    # Initialize matrices for storing probabilities and paths
    V = np.zeros((n_states, T))  # Stores the maximum probabilities for each state at each time step
    path = np.zeros((n_states, T), dtype=int)  # Stores the most likely previous state for each state

    # Initialization step: Initialize the first column of V
    for s in range(n_states):
        V[s, 0] = initial_prob[s] * emission_prob[s, obs_indices[0]]
        path[s, 0] = s

    # Recursion step: Fill in the rest of V and path matrices
    for t in range(1, T):
        for s in range(n_states):
            # Calculate the max probability for state `s` at time `t`
            max_prob = -1
            prev_state = -1
            for s_prev in range(n_states):
                prob = V[s_prev, t-1] * transition_prob[s_prev, s] * emission_prob[s, obs_indices[t]]
                if prob > max_prob:
                    max_prob = prob
                    prev_state = s_prev
            V[s, t] = max_prob
            path[s, t] = prev_state

    # Termination step: Find the most likely final state
    best_last_state = np.argmax(V[:, T-1])
    best_path = [best_last_state]

    # Backtrack through the path matrix to find the best path
    for t in range(T-1, 0, -1):
        best_last_state = path[best_last_state, t]
        best_path.insert(0, best_last_state)

    # Convert state indices back to state names
    best_path_states = [states[state] for state in best_path]

    return best_path_states, V

# Run the Viterbi algorithm on the observation sequence
best_path, V = viterbi(obs_indices, transition_prob, emission_prob, initial_prob)

# Output the result
print("Most likely sequence of states:", best_path)
print("Probability matrix (V):\n", V)


Most likely sequence of states: ['Sunny', 'Cloudy', 'Rainy']
Probability matrix (V):
 [[0.48     0.0672   0.      ]
 [0.06     0.0576   0.004608]
 [0.01     0.0144   0.010368]]
